apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels:
    run: gitlab
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30080
      name: http
    - port: 443
      protocol: TCP
      nodePort: 30043
      name: https
    - port: 22
      protocol: TCP
      nodePort: 30022
      name: ssh
  selector:
    run: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      run: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        run: gitlab
    spec:
      containers:
        - name: gitlab
          image: yrzr/gitlab-ce-arm64v8
          ports:
            - containerPort: 443
            - containerPort: 80
            - containerPort: 22
