Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define "ybahlaouS" do |controlS|
      controlS.vm.hostname = "ybahlaouS"
      controlS.vm.network "private_network", ip: "192.168.56.110"
      controlS.vm.provider "virtualbox" do |v|
          v.memory = 1024
          v.cpus = 3
          v.name = "ybahlaouS" # name appears in the VirtualBox GUI
          v.customize ["modifyvm", :id, "--name", "ybahlaouS"]
      end
      controlS.vm.provision "shell", path: "scripts/init-master-node.sh"
  end
end
